export * from './lib/dom-operations';
export * from './lib/globalProvider';
export * from './decorators/index';
export * from './decorators/events.decorator';
export * from './decorators/properties.decorator';
export * from './services/observer.service';
export * from './types/common';
export * from './components/base.component';
import JSX from './components/jsx';
export default JSX;
