export * from './lib/dom-operations';
export * from './lib/globalProvider';
export * from './lib/router/routes';
export * from './lib/router/router';
export * from './decorators/index';
export * from './services/observer.service';
export * from './types/common';
export * from './types/servicetype';
export * from './types/type';
export * from './components/base.component';
export * from './components/lifecycle.enum';
import JSX from './components/jsx';
export default JSX;
